import { Inter } from 'next/font/google'
import Providers from './(components)/providers'
// In your _app.js or a component
import 'katex/dist/katex.min.css';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
                                       children,
                                   }: {
    children: React.ReactNode
}) {
    return (
        <>
            {children}
        </>
    )
}